networks:
  YOUR_EXISTING_NETWORK:
    external: true

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile_backend
    container_name: hevy_backend
    restart: unless-stopped
    # ports: # Optional external exposure
    #  - 5000:5000
    environment:
      - X_API_KEY=klean_kanteen_insulated
    hostname: hevy_backend
    networks:
      - YOUR_EXISTING_NETWORK

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile_frontend
    container_name: hevy_frontend
    restart: unless-stopped
    ports:
      - 8123:8080
    depends_on:
      - backend
    hostname: hevy_frontend
    networks:
      - YOUR_EXISTING_NETWORK
